#!/usr/bin/python

import sys
import os
from   optparse       import OptionParser
from   sudoku.sudoku  import Puzzle
from   sudoku.Version import VERSION

cmd    = OptionParser (version = "%%prog %s" % VERSION)

cmd.add_option \
    ( "-a", "--author"
    , dest    = "author"
    , help    = "Change default author info"
    )
cmd.add_option \
    ( "-c", "--colorconstrained"
    , dest    = "colorconstrained"
    , help    = "Add color constraint"
    , action  = "store_true"
    )
cmd.add_option \
    ( "-d", "--diagonal"
    , dest    = "diagonal"
    , help    = "Add diagonality coloring"
    , action  = "store_true"
    )
cmd.add_option \
    ( "-t", "--title"
    , dest    = "title"
    , help    = "Change default title info (defaults to given filename)"
    , default = ''
    )
(opt, args) = cmd.parse_args ()
file = sys.stdin
name = ''
if len (args) > 1 :
    cmd.error ("Only 1 argument accepted")
elif len (args) == 1 :
    file = open (args [0])
    name = args [0]
if opt.title :
    name = opt.title

x = Puzzle  (diagonal = opt.diagonal, colorconstrained = opt.colorconstrained)
x.from_file (file)
x.as_tex    (title = name, author = opt.author)

